#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Installing raspi-gpio3-shutdown service..."

echo "Installing required packages"
sudo apt install python3-pigpio python3-gpiozero python3-systemd

echo "Enabling and starting pigpiod service"

if [ ! -e /etc/gpiozero_pin_factory.conf ]
  then
    sudo cp gpiozero_pin_factory.conf /etc
  else
    echo "File '/etc/gpiozero_pin_factory.conf' already exists. Did not overwrite."
fi

sudo systemctl enable pigpiod
sudo systemctl start pigpiod

if [ -e /etc/raspi-gpio3-shutdown.conf ]
  then
    read -p "Overwrite existing configuration file '/etc/raspi-gpio3-shutdown.conf' (y/N)?" ov
  else
    ov = "y"
fi

if [ "$ov" == "y" -o "$ov" == "Y" ]
  then
    sudo cp raspi-gpio3-shutdown.conf /etc
fi

if  [ -e /usr/local/bin/raspi-gpio3-shutdown.py ]
  then
    echo "Updating service script '/usr/local/bin/raspi-gpio3-shutdown.py' (temporarily stopping service)"
    sudo systemctl stop raspi-gpio3-shutdown
fi

sudo cp raspi-gpio3-shutdown.py /usr/local/bin/
sudo chmod +x /usr/local/bin/raspi-gpio3-shutdown.py

sudo cp raspi-gpio3-shutdown.service /lib/systemd/system
sudo chmod +x /lib/systemd/system/raspi-gpio3-shutdown.service

if id -nGz "pi" | grep -qzxF "gpio"
  then
    echo "User 'pi' already belongs to group 'gpio'."
  else
    sudo usermod -a -G gpio pi
fi

echo "Starting raspi-gpio3-shutdown service..."

sudo systemctl enable raspi-gpio3-shutdown
sudo systemctl daemon-reload
sudo systemctl start raspi-gpio3-shutdown

echo "raspi-gpio3-shutdown service installed."
